### ISSUE TITLE
I can't get app to work

### ISSUE THREAD

**Issue by lpt2007** [kprestel/appdaemon-climate#2]
For start I try one climate, like this:

   
```
climatge_climate:
  module: climatge
  class: Climate
  thermostat: climate.hallway_climate
  weather_sensor: sensor.home_temperature
  mode_switching_enabled: true
  max_temperature: 26
  min_temperature: 18
  inside_temperature_sensors:
    livingroom:
      sensors:
          - sensor.livingroom_thermostat_current_temperature
    kitchen:
      sensors:
          - sensor.kitchen_thermostat_current_temperature
    childrens:
      sensors:
          - sensor.childrens_current_temperature
    bedroom:
      sensors:
          - sensor.bedroom_current_temperature
    hallway:
      sensors:
          - sensor.hallway_climate_current_temperature
          - sensor.hallway_thermostat_current_temperature
    bathroom:
      sensors:
          - sensor.bathroom_current_temperature
          - sensor.bathroom_thermostat_current_temperature
    wc:
      sensors:
          - sensor.wc_current_temperature
  preferences:
    morning:
      time: input_datetime.climatge_morning
      temperature: input_number.climatge_morning_temp
      target_area: livingroom, kitchen, childrens, bedroom, hallway, wc
    daytime:
      time: input_datetime.climatge_daytime
      temperature: input_number.climatge_daytime_temp
      target_area: livingroom, kitchen, childrens, bedroom, hallway, wc
    evening:
      time: input_datetime.climatge_evening
      temperature: input_number.climatge_evening_temp
      target_area: livingroom, kitchen, childrens, bedroom, hallway, wc
    bedtime:
      time: input_datetime.climatge_bedtime
      temperature: input_number.climatge_bedtime_temp
      target_area: livingroom, kitchen, childrens, bedroom, hallway, wc
    morning_bathroom:
      time: input_datetime.climatge_bathroom_morning
      temperature: input_number.climatge_bathroom_morning_temp
      target_area: bathroom
    daytime_bathroom:
      time: input_datetime.climatge_bathroom_daytime
      temperature: input_number.climatge_bathroom_daytime_temp
      target_area: bathroom
    evening_bathroom:
      time: input_datetime.climatge_bathroom_evening
      temperature: input_number.climatge_bathroom_evening_temp
      target_area: bathroom
    bedtime_bathroom:
      time: input_datetime.climatge_bathroom_bedtime
      temperature: input_number.climatge_bathroom_bedtime_temp
      target_area: bathroom
```

Is this correct configuration?

error:
```
2022-03-16 18:05:47.629845 WARNING AppDaemon: Unable to find module module climatge - 'climate' is not initialized
2022-03-16 18:05:47.632928 WARNING AppDaemon: Unable to find module climate - initialize() skipped
```
