### ISSUE TITLE
climate won't turn off after temperature is reached

### ISSUE THREAD

**Issue by lpt2007** [kprestel/appdaemon-climate#3]
Hi,

Climate AC won't turn off after temperature is reached, just change temperature to value I set?

**Comment by kprestel** [comment]
I think I need to update the README to explain this more.

What temperature has been reached?

**Comment by lpt2007** [comment]
I set in living room as target area, but when temperature is reached ac won't turn off ( only lowers the temperature).

Here is configuration:
```
### CLIMATGE APP    
climate:
  module: climate
  class: Climate
  thermostat: climate.hallway_climate
  weather_sensor: sensor.home_temperature
  mode_switching_enabled: true
  max_temperature: 26
  min_temperature: 10
  inside_temperature_sensors:
    livingroom:
      sensors:
          - sensor.livingroom_thermostat_current_temperature
    kitchen:
      sensors:
          - sensor.kitchen_thermostat_current_temperature
    childrens:
      sensors:
          - sensor.childrens_thermostat_current_temperature
          - sensor.childrens_current_temperature
    bedroom:
      sensors:
          - sensor.bedroom_current_temperature
    hallway:
      sensors:
          - sensor.hallway_climate_current_temperature
  preferences:

    morning:
      input_time: input_datetime.climate_morning
      input_temperature: input_number.climate_morning_temp
      target_area: livingroom
    daytime:
      input_time: input_datetime.climate_daytime
      input_temperature: input_number.climate_daytime_temp
      target_area: livingroom
    evening:
      input_time: input_datetime.climate_evening
      input_temperature: input_number.climate_evening_temp
      target_area: livingroom
    bedtime:
      input_time: input_datetime.climate_bedtime
      input_temperature: input_number.climate_bedtime_temp
      target_area: livingroom
```
